<?php
	/*SLIDER 1.0.1*/
	'id_slider_1_0_1' => array(
		'key' => 'id_slider_1_0_1',
		'name' => 'slider_1_0_1',
		'label' => 'Slider 1.0.1',
		'display' => 'block',
		'sub_fields' => array(
			array(
				/* Tab Slider Desktop*/
				'key' => 'id_slider_1_0_1_tab1',
				'label' => 'Slider Desktop',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'id_slider_1_0_1_sub1',
				'label' => 'Slide Desktop',
				'name' => 'slide_pc',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'insert' => 'append',
				'library' => 'all',
				'min' => '',
				'max' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				/* Tab Slider Mobile*/
				'key' => 'id_slider_1_0_1_tab2',
				'label' => 'Slider Mobile',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'id_slider_1_0_1_sub2',
				'label' => 'Slide Mobile',
				'name' => 'slide_mb',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'insert' => 'append',
				'library' => 'all',
				'min' => '',
				'max' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'min' => '',
		'max' => '',
	),
	/*END SLIDER 1.0.1*/
?>